### ISSUE TITLE
documentation: $and: '(orientation: landscape)')

### ISSUE THREAD

**Issue by ManfredWisniewski** [sass-mq/sass-mq#105]
#I cannot figure out how  to use $and: '(orientation: landscape)') in sass_mq

Can you please elaborate in the documentation?

Thank you!

**Comment by kaelig** [comment]
Hi @ManfredWisniewski, thank you for using sass-mq!

May I ask: what are you trying to achieve, and what seems unclear?

**Comment by ManfredWisniewski** [comment]
Hi @kaelig Thanks for your answer!
I misread the example in your documentation. I thought that somehow sass-mq has its own handling for orientation.  But then I figured out its just a combination of sass-mq with the normal media query. :)
