### ISSUE TITLE
Different behavior for $until

### ISSUE THREAD

**Issue by iusenko** [sass-mq/sass-mq#106]
I have defined variable for breakpoints
```
$mobile:  320px;
$tablet:  768px;
$laptop:  990px;

$mq-breakpoints: (
  mobile:           $mobile,
  tablet:           $tablet,
  laptop:           $laptop
);
```
and when I am using $until it has different behavior
```
 @include mq($until: laptop) {
    font-size: 12px
  }

 @include mq($until: $laptop) {
    font-size: 12px
  }
```
the result is :
```
@media (max-width: 61.865em) {  // max-width: 989px
    .class {
        font-size: 12px
    }
}
@media (max-width: 63.75em) { // max-width: 990px
    .class {
        font-size: 12px
    }
}
```
I think it is wrong behavior and in both cases should be max-width: 989px.  What do you think?

**Comment by kaelig** [comment]
This is the expected behavior: passing a number instead of a reference to a named breakpoint should return that number.

**Comment by iusenko** [comment]
I think it is not obvious. If I am using $until it have to be until the number. Why I should remember that there is difference? And for consistent it would be better to do the same behavior for both cases.

**Comment by kaelig** [comment]
The reasoning is that people passing a number would want `$until` to exactly equal that number.

The recommended usage is sticking to breakpoint references instead of passing numbers. Feel free to fork or copy-paste sass-mq and adapt it to your needs if the default behavior doesn't work for you ❤️

**Comment by kaelig** [comment]
Final note: passing numbers to `mq()` is not documented because it's not the recommended use. Passing keywords is the best practice that sass-mq is trying to enforce.
