### ISSUE TITLE
Documentation settings chores

### ISSUE THREAD

**Issue by kaelig** [sass-mq/sass-mq#108]
Hey @sndrs, I need your help to change some settings on this repo 👋

- [x] GitHub Pages: set the gh-pages source to **"master branch /docs folder"**
    ![ ](https://help.github.com/assets/images/help/pages/select-gh-pages-or-master-as-source.png)
- [x] Set this repo's URL to `https://sass-mq.github.io/sass-mq` (https instead of http)

Thank you!

**Comment by sndrs** [comment]
done and done!

**Comment by kaelig** [comment]
Fab, thank you!
