### ISSUE TITLE
Subpixel issue in FF and IE11

### ISSUE THREAD

**Issue by mikemai2awesome** [sass-mq/sass-mq#113]
After extensive testing, I believe this value should go down one more decimal for it to work perfectly with FF and IE11. It should be `0.001em` instead of `0.01em`.

https://github.com/sass-mq/sass-mq/blob/47cd6b1156d35a702edd3fbed0bcd285dcd95d29/_mq.scss#L195

**Comment by kaelig** [comment]
Thank you for using sass-mq and for the bug report!

Could you please post screenshots and detailed specs of all browsers tested?

**Comment by mikemai2awesome** [comment]
![bp](https://user-images.githubusercontent.com/3027663/41804238-eee568a2-7660-11e8-8273-acd1a1404237.jpg)

```css
.half {
  @include mq(tablet) {
    background: red;
  }
}
```

The tablet breakpoint is not exactly at 740 if the browser zoom level is not at 100%.

**Comment by kaelig** [comment]
Thanks so much, this is very helpful! Does the 0.001em fix work better in all browsers / devices?

**Comment by mikemai2awesome** [comment]
Yes. 0.001em makes it work perfectly.

**Comment by kaelig** [comment]
@tzi seems to have spotted an issue with a `0.001em` separation:

> So we have to use a tinier separation between our two media-queries to prevent a gap between them. If we choose a too small separation, for example 0.001em, there is a risk that the browser rounded the two media-queries to the same values.

https://tzi.fr/css/prevent-double-breakpoint/

It feels like we may be trading one problem for another :/

**Comment by tzi** [comment]
> It feels like we may be trading one problem for another :/

Sad truth...
I will program to make some new tests, mines are 4 years old now.

**Comment by mikemai2awesome** [comment]
I think the problem lies in the conversion math, at some point, something is not going to add up. Would this be a problem if breakpoints are always defined in `em` and there is no conversion from `px` to `em`?

**Comment by kaelig** [comment]
Unless I'm misunderstanding something in your question, I'm not sure how this would help, considering the mixin would remove `0.01em` anyway?

**Comment by mikemai2awesome** [comment]
Right, separate issue.

So what have you find in your own browser testing? Is there a solution to address this?

**Comment by kaelig** [comment]
I haven't had time to get to it, sorry! I'd say the only solid solution is to use media queries level 4, with `<=`, `>=`, `<`, `>` operators.

**Comment by kaelig** [comment]
Closing this as this seems to be a rare occurrence.

Feel free to open a pull request, I'll be happy to publish a beta so we can rally a few users of sass-mq that can attest that this is not breaking existing behavior.
