### ISSUE TITLE
Function mq-get-breakpoint-width finished without @return

### ISSUE THREAD

**Issue by JessicaYeoh** [sass-mq/sass-mq#114]
this function finished without @return??

unsure if this a common issue.

**Comment by kaelig** [comment]
Hey @JessicaYeoh - thanks for using sass-mq!

Can you share some of your code?

Seems like you may be running into an issue where the breakpoint’s name wasn't found.

**Comment by JessicaYeoh** [comment]
i am using it in a laravel project and the only thing i have done so far is import sass-mq into my sass file.

As follows:
@import '~sass-mq/mq';

it then immediately comes up with the error i mentioned

**Comment by kaelig** [comment]
Thanks, I'll need more information to reproduce:
- what's the version of Sass and is it node-sass or something else?
- what does the webpack config look like (if any)?
- What's the version of Node.js?

Anything else to help reproduce the issue would be very helpful.

**Comment by JessicaYeoh** [comment]
sass version is v10.4.1

This is the package.json file:
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.18",
        "bootstrap": "^4.0.0",
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-mix": "^2.1.14",
        "lodash": "^4.17.4",
        "popper.js": "^1.12",
        "vue": "^2.5.7"
    },
    "dependencies": {
        "jquery-modal": "^0.9.1",
        "mq-scss": "^2.1.4",
        "owl.carousel": "^2.3.4",
        "sass-mq": "^5.0.0"
    }
}

i'm using Laravel Mix if that helps

**Comment by kaelig** [comment]
10.4.1 is the version of Node, I take it.

It'd be very useful if you could set up a reduced test case in a repository I can access (or give me access to your repo), as I'm not sure how to reproduce the bug with what you gave me.

**Comment by kaelig** [comment]
Closing this as it is lacking a reduced test case.
