### ISSUE TITLE
Stop converting media queries to em

### ISSUE THREAD

**Issue by seothemes** [sass-mq/sass-mq#116]
Reopening #59. This no longer works:

```scss
// Override width handling with pixels
@function mq-width-override($px, $base-font-size) {
  @if unitless($px) {
    @return $px * 1px;
  }
  @if unit($px) == em {
    @return $px / 1em * $base-font-size;
  }
  @return $px;
}

@import 'path/to/mq';
```

Users should be able to choose the media query unit. There needs to be a way to override `mq-px2em`.

**Comment by kaelig** [comment]
Thanks for using sass-mq! The final resolution for this issue can be found here: https://github.com/sass-mq/sass-mq/pull/65#issuecomment-198752907

**Comment by seothemes** [comment]
Yes but also see https://adamwathan.me/dont-use-em-for-media-queries/

The tests in the blog post you referenced were incorrect, therefor pixels are still the best option.

Why not support both? Would you accept a PR?

**Comment by kaelig** [comment]
> The tests in the blog post you referenced were incorrect

How so? The author of https://zellwk.com/blog/media-query-units/ does mention Safari doesn't handle zoom + em media queries correctly and still comes to the conclusion that em-based media queries are the most sensible choice.

Sass MQ is an opinionated library that goes in the sense of enabling accessibility, not hindering it. Hopefully Safari fixes their implementation! There is a bug open here: https://bugs.webkit.org/show_bug.cgi?id=156687 – feel free to get in touch with the WebKit folks to try to get the work prioritized.

In the mean time, if you really need pixel-based media queries I'd encourage you to use this fork: https://github.com/flea89/sass-mq
