### ISSUE TITLE
Using sass-mq with webpack / create-react-app looks like broken

### ISSUE THREAD

**Issue by pieplu** [sass-mq/sass-mq#118]
Looks the same bug as #114

I guess than webpack sass-loader / create-react-app config is more strict now. (it works on the past)

Step to reproduce:
- Create an app with [create-react-app](https://facebook.github.io/create-react-app/)
- install sass-mq with npm
- install node-sass and import a stylesheet who use sass-mq [doc](https://facebook.github.io/create-react-app/docs/adding-a-sass-stylesheet)
- `npm start`

Should trigger the same error than #114

**Comment by kaelig** [comment]
Bonjour Alexis,

I couldn't reproduce the issue myself.

Can you try this code in `App.scss`?

```scss
// App.scss
@import '~sass-mq';

@include mq(mobile) {
    body {
		background: red;
    }
}
```

It works locally on my machine with the latest create-react-app.

---

On certain stacks, you may need to import it this way: `@import '~sass-mq/mq';`.

See a working example in this CodeSandbox: https://codesandbox.io/s/04xqpljp60

Hope it helps, and please reopen this issue if the problem persists!

**Comment by pieplu** [comment]
Bonjour!

Now, I'm not able to reproduce too. I have updated CRA since the report, maybe it's an issue of libsass or other.

Have a nice day!
