### ISSUE TITLE
Breakpoints at wrong width

### ISSUE THREAD

**Issue by ricardo-afonso** [sass-mq/sass-mq#122]
I've ran into a issue and I'm not entirely sure what's causing it.

Currently building a website, where I have on the `_variables.scss` a `$base-font-size: 14pt`. This file is imported before the `_mq.scss` file.

In another file, I use it in the `html` selector to set a global font size, so that it gets inherited down.  Following that, and to keep things consistent, I've set the `$mq-base-font-size` on `_mq.scss` to be equal to `$base-font-size`.  Also added to new, bigger, breakpoints to the breakpoint list, but I don't think that has much impact on what's happening, since i've tested without them. 

I've noticed now that the breakpoints happen at the wrong widths of the viewport ( see attached ). Tried tracking down the root cause of the issue and it seems to lie somewhere on the  `mq-px2em` function. Removing it's call through the file, solves the issue and the breakpoints happen at the right widths. I do however lose some functionality, such as the use of the `$until`. 

![image](https://user-images.githubusercontent.com/14220272/60891057-7bd4b180-a254-11e9-8277-2f74e8a3992d.png)

**Comment by kaelig** [comment]
Hi, thank you for using sass-mq!

`14pt` is using the `pt` unit, which may not work as expected.

Furthermore, `1em` is always equal to 16px in media queries – the `_mq.scss` file makes it look like `$mq-base-font-size` a configurable setting, but it’s a mistake that we should fix.

Leave `$mq-base-font-size` as is, and everything should work as expected.

**Comment by ricardo-afonso** [comment]
Thanks. `$mq-base-font-size` does seem like a configurable setting.  I even tried to use 19px as a base font size value ( It's the closest pt to px converted number) and the issue persisted. 

Leaving it at 16px does solve the issue, thanks!
