### ISSUE TITLE
Empty mixin output when $mq-responsive is false can break extending placeholders

### ISSUE THREAD

**Issue by nickcolley** [sass-mq/sass-mq#130]
When using mq inside a placeholder it can return empty when responsive is set to false which makes the placeholder throw an error when being extended.

Test case:
https://gist.github.com/nickcolley/4d93df08909b533b196ed5581ef778c4

https://www.sassmeister.com/gist/4d93df08909b533b196ed5581ef778c4

## Actual

```log
Error: "html" failed to @extend "%until-mobile-only".
       The selector "%until-mobile-only" was not found.
       Use "@extend %until-mobile-only !optional" if the extend should be able to fail.
        on line 12 of app/assets/sass/application-ie8.scss
>>     @extend %until-mobile-only;

   ------------^
```

## Expected

Perhaps sass-mq could check if there's content to output and give users a more meaningful error using [content-exists()](https://sass-lang.com/documentation/modules/meta#content-exists).

I'm not too sure if there's a sensible solution here, but would welcome your thoughts. We may be able to contribute the change if you guide us here.

**Comment by kaelig** [comment]
Thank you for opening that issue, @nickcolley! Also stoked to see you're now working on Origami at the FT – I absolutely loved working on that project and with such brilliant people ❤️ 

I have a feeling the usage of `$responsive: false` is becoming rarer and rarer, so I'll just quote [your workaround](https://github.com/alphagov/govuk-frontend/issues/1674#issuecomment-589615009) below, in case anybody is running into this issue:

> * use the `!optional` flag when extending, for example:
> 
> ```css-scss
> %display-mobile-only {
>   @include govuk-media-query($until: mobile) {
>     display: none;
>   }
> }
> 
> .app-sidebar-hr {
>    // using !optional to work around the placeholder being empty in Internet Explorer 8 builds.
>   @extend %display-mobile-only !optional;
> }
> ```
