### ISSUE TITLE
Would it be possible to support rem as units as well?

### ISSUE THREAD

**Issue by landwire** [sass-mq/sass-mq#134]
I wanted to use rem as a unit for my breakpoints, but sass-mq did not like it:

```
node_modules/sass-mq/_mq.scss
Error: 4.625em*rem/px isn't a valid CSS value.
        on line 111 of node_modules/sass-mq/_mq.scss, in mixin `mq`
        from line 53 of src/sass/utilities/_typography.scss, in mixin `typo`
        from line 25 of src/sass/basics/_globals.scss
        from line 3 of src/sass/basics/_basics.scss
        from line 9 of src/sass/main.scss
>>     @return ($px / $base-font-size) * 1em;
```

That's because of the mq-px2em function. Is it somehow possible to use rem anyway?

**Comment by kaelig** [comment]
Hi, thank you for using Sass MQ, and apologies for the late reply.

`em` and `rem` are equivalent in media queries (based on a 16px root font size). This means `1rem` = `16px` in a media query, but this isn't necessarily true in other parts of the code.

```css
:root {
  font-size: 62.5%; /* =10px */
}

@media (min-width: 10rem) { /* =160px */
  div { width: 10rem; }  /* =100px */
}

```

This possible discrepancy introduces confusion.

For that reason, as a library I think Sass MQ should default to `em` units in media queries.

---

If you're looking for a different behavior, I'd recommend copying `_mq.scss` in your project and adapt the code to your needs.

I hope this helps!
