### ISSUE TITLE
README fix in "Changing Media Type" section

### ISSUE THREAD

**Issue by seanmacgillivray** [sass-mq/sass-mq#150]
Where the invocation of the mq mixin uses the first and only argument without specifying $from or $until, the resultant CSS has a min-width media query, not a max-width. Doublechecked in Sassmeister.

**Comment by seanmacgillivray** [comment]
I've got a fix prepped for this already and am happy to contribute!

**Comment by kaelig** [comment]
Thank you for using sass-mq! This behavior is on purpose, but feel free to fork the project if that's something you'd prefer to behave differently in your projects.
