### ISSUE TITLE
When will v6.0.0 be out of beta

### ISSUE THREAD

**Issue by siiron** [sass-mq/sass-mq#151]
Any update on when 6.0.0-beta will be officially released as 6.0.0? Due to security policies in our CICD environment, we're not allowed to move to production with any dependencies marked as `alpha` or `beta`.

We are moving from node-sass to sass these days and need an updated version of sass-mq using `math.div` instead of the `/`-operator.

**Comment by kaelig** [comment]
I should have some time over the next few weeks! In the meantime, I'd recommend copy-pasting this dependency directly in your project's file structure (.scss file + license).
