### ISSUE TITLE
Invalid CSS error message 

### ISSUE THREAD

**Issue by emmaYugen** [sass-mq/sass-mq#154]
Hello. 
I'm working a project with npm 8.5.5 and node v16.15.0.
I'm using gulp (v4.0.2) to build my front assets. 
I'm importing the package in my css : 
`@import '../../node_modules/sass-mq/mq';`  

I always used this package on my other projects, but it's the first time I get this error on build : 
```node_modules/sass-mq/_mq.scss Error: Invalid CSS after "  @if math": expected expression (e.g. 1px, bold), was ".is-unitless($px)```

Maybe it's because of the node / npm version I'm using... it's the first time I upgraded to the latest versions after a long time, so I never saw this error before. 

Is this a known issue or something ? 
Could anyone help ?

**Comment by emmaYugen** [comment]
Well I found out it's because apparently, `node-sass` doesn't support sass module. 
but I used it on older projects and it worked. 
Maybe they don't support it anymore... 
Apparently, it's needed to switch on `dart-sass` for this feature. 
It's the first time I hear about this.

**Comment by kaelig** [comment]
Hi, thank you for using Sass MQ!

Perhaps this will help: https://github.com/sass-mq/sass-mq#backward-compatibility-with-import

> Just in case you need to have backward compatibility and want to use `@import` instead of `@use`, you can do so by importing `_mq.import.scss` instead of `_mq.scss`.

Alternatively, use version `^4.0.2` of `sass-mq`, which comes with default support for node-sass.

Hope this helps!
