### ISSUE TITLE
Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by raf-vs** [sass-mq/sass-mq#157]
Hi,

Using sass-mq with Dart Sass gives the following deprecation warning:

`Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.`

Since locally editing "_mq.scss" in my node_modules isn't a good long-term solution (Also: it's a shared project so...)
Is there any way, outside of editing "_mq.scss", to remove/avoid this warning?

I would like to keep using sass-mq but also use the latest sass and other tools.
Ok, it's just a warning but it would be nicer/cleaner/better to have no (deprecation) warnings or errors at all.

Some extra info:
node: 16
sass-mq: ^5.0.0
sass:  ^1.52.3

Thanks in advance!

**Comment by rekomat** [comment]
Hej @raf-vs – This is fixed with `v6.0.0`. Check #142 for details.

**Comment by kaelig** [comment]
Closing this as it was fixed in v6.
