### ISSUE TITLE
error reading values after mobile

### ISSUE THREAD

**Issue by davidangel** [sass-mq/sass-mq#20]
[gulp-sass] /media/sass/modules/mq:13: error: error reading values after mobile

Any idea what might be causing this issue?

**Comment by PatrickBrady** [comment]
Hi Kealig-
Really eager to use your mixin but I'm getting a similar error.

error sass/theme1.scss (Line 35 of sass/mixins/_mq.scss: Invalid CSS after "    mobile": expected ")", was ":  320px,")

It's a mapping issue I guess I'm running the latest version of Sass and Compass. I just reinstalled both as I was sure that was the issue.

**Comment by kaelig** [comment]
Thank you for using Sass MQ!

Can you please let me know what version of Sass is running on the machine?

**Comment by PatrickBrady** [comment]
Hi Kaellig-
Thanks for responding. I'm running 3.4.14, Selective Steve.

**Comment by kaelig** [comment]
Interesting.

What command do you run to compile the project?
Do you use a program such as CodeKit to compile it? Or the `sass` command in the terminal?

**Comment by PatrickBrady** [comment]
I'm using FireApp right now. I haven't gotten situated with Grunt yet.

**Comment by kaelig** [comment]
It looks like FireApp uses its own version of Sass (not the one installed on the system). So it could be that an outdated version of FireApp is installed on your system. Can you update FireApp and try again?

**Comment by PatrickBrady** [comment]
oh, that would make sense. Maybe I should try from the command line or using Scout

**Comment by kaelig** [comment]
Looks like you can configure what version of Sass you'd like to run in FireSass. See http://fireapp.kkbox.com/doc/preference.html

**Comment by PatrickBrady** [comment]
Thanks so much Kaelig for your help. I think there could be a problem with my version of Sass right now

**Comment by kaelig** [comment]
No problem, and please let me know if you still have trouble making it work.

**Comment by PatrickBrady** [comment]
You were a big help. Once I can get Sass working properly again I'll try again.

Thanks!
