### ISSUE TITLE
Active breakpoint in a global variable.

### ISSUE THREAD

**Issue by ngryman** [sass-mq/sass-mq#48]
Hey,

This is just an idea, I wanted to ask you if this makes sense.
I would like to be able to know which active breakpoint I'm writing code for. This would allow me to make decisions based on it (out of this ticket scope).

The basic idea would be to declare a global variable with the default breakpoint as initial value. The default value may depend on the approach used (mobile first, desktop first). So it should be a configurable variable:
```scss
$mq-default-breakpoint: mobile !default;
$mq-active-breakpoint: $mq-default-breakpoint;
```

This variable would change when calling `mq()`. It would be set to the active breakpoint just before the `@content` and then reset to its default value. Roughly something like that:
```scss
$mq-active-breakpoint: $until; // or $from? or more complex?
@content;
$mq-active-breakpoint: $mq-default-breakpoint;
```

The code executed in `@content` would then be aware of its *responsive context*, which could be pretty powerful.

The problem here is to define the meaning of *the active breakpoint*. In a mobile first approach, it would probably be the value of `$from`, in a desktop first approach it would probably be `$until`.
What happens if we specify both? Perhaps we could define a *direction*.

But first, does this makes sense to you? :neckbeard:

**Comment by kaelig** [comment]
Thanks for using Sass MQ, Nicolas.

This is a brilliant idea :sparkles:, I had never thought about it, but I can see the power of this feature!

Would you care to open a Pull Request for it?
