### ISSUE TITLE
Support IE8 with media queries

### ISSUE THREAD

**Issue by morganfeeney** [sass-mq/sass-mq#50]
Have you considered rather than creating a separate stylesheet and detecting IE8, that you create your base styles which incorporate a fixed width and then override them with a min-width media query - which will be excluded from IE8 anyway as it's not supported?

**Comment by kaelig** [comment]
Thanks for the interesting though, @mofeenster.

I believe you can already do what you suggest (manually) but I'm not sure how we could automate it using Sass. Any thoughts? Also, it sounds like it would lead to a lot of code. What do you think?

----
There's also another way to target IE8 which is using a `@media` hack:

```scss
/// Target styles at Internet Explorer 8 only
@mixin targetIE8 {
	@media \0screen {
		@content;
	}
}
```

I used this technique for the grid I've built at the Financial Times (which is responsive and serves an IE8-specific version at the same time): http://sassdoc.webservices.ft.com/v1/sassdoc/o-grid@v3.0.3#mixin-oGridTargetIE8

**Comment by mofeenster** [comment]
I'm looking at this from the point of CSS only, so haven't gone into the depths of automation as yet, but would be happy to at some point soon maybe.

The way I see it is if you create your responsive layout which expands and contracts to a maximum width where it is supported, then surely your layout will work in exactly the same fashion with a fixed width which you can designate to IE8.

I wrote a short article on this: http://www.morganfeeney.com/web-development/legacy-issues/support-ie8-using-media-queries

Of course you are probably already aware of this as you point out that  you can do this manually. But what I really like about what I mention is the fact that there is no need for a hack, it's purely CSS features.

**Comment by kaelig** [comment]
I'm not sure I see the benefit of the technique described in the article, since creating a separate stylesheet is really simple and allows for a mobile-first approach (which, if I undertsand well, you propose we could use a IE8-first approach, and then reset styles).

**Comment by mofeenster** [comment]
Unless you define 'First' as being about the fixed width being first, which gets overridden by a media query, it's a progressive approach. Adding an extra stylesheet isn't necessary IMO, unless you plan to go crazy and want to be more organised.

**Comment by kaelig** [comment]
I see your point. Can you show how would you do it with Sass?

**Comment by mofeenster** [comment]
To be continued...
I will come back to you with some semblance of an example as soon as possible.

**Comment by kaelig** [comment]
Closing this, @morganfeeney feel free to re-open it when there's an example you'd like to share.

**Comment by morganfeeney** [comment]
Hi, yes sorry about the delay. Thought I'd be working on some SASS stuff at work which would lead me to that example. Ended up using LESS and relearning stuff I had learnt with SASS, I'll get to it and will re-open later.

Thanks
