### ISSUE TITLE
Travis badge in readme shows "build unknown"

### ISSUE THREAD

**Issue by kaelig** [sass-mq/sass-mq#53]
Which is weird because it builds: https://travis-ci.org/sass-mq/sass-mq/builds/66027987

@sndrs is there something to activate in the settings of the repo or directly on Travis?

**Comment by magsout** [comment]
have push a commit after add travis on this repo ?

**Comment by kaelig** [comment]
Yes and I'm pretty sure it used to show the correct badge. Might be a travis bug tbh.

**Comment by sndrs** [comment]
yeah it did work previously

**Comment by kaelig** [comment]
@sndrs is it activated here? https://travis-ci.org/profile/sass-mq

**Comment by kaelig** [comment]
@sndrs can you have a look?

**Comment by kaelig** [comment]
Looks like this fixed itself.
