### ISSUE TITLE
Stop converting media queries to em

### ISSUE THREAD

**Issue by fvsch** [sass-mq/sass-mq#59]
Hi,

sass-mq currently converts all breakpoints to `em` values, using a ratio of `1em = 16px` (that ratio can be changed but it would definitely create unexpected behavior for users, so it's a good thing the variable for that is not advertised). The rationale for converting to `em` was [browser limitations (January 2014 post)](https://css-tricks.com/zooming-squishes/) with zooming. More specifically, it was a WebKit bug, affecting Chrome and Safari, which has since been fixed (around 2014?).

No zoom issue with `px` media queries in my tests on:
- Recent and older Firefoxes
- IE 9, IE 11
- Chrome 30
- Safari 8, Safari 6.1 on OS X

So it seems safe to say it's a non-issue now. What's more, using `em` media queries as substitutes for pixels can pose a risk if end users have changed the browser's base font size to something that is not 16px (to be confirmed; not sure if it does impact `em`-based media queries in all browsers).

I suggest that sass-mq stop converting pixels to ems and allow users to set breakpoints in ems in `$mq-breakpoints` (if that is not already the case). For `max-width` queries, a pixel breakpoint should be reduced by one, e.g. `(max-width: 799px)` if the breakpoint is `800px`.

**Comment by shaunbent** [comment]
> What's more, using `em` media queries as substitutes for pixels can pose a risk if end users have changed the browser's base font size to something that is not 16px

Media queries defined with `em` are *always* based off 16px no matter what the base font size is set to. 

I also thought it could be changed by the user but it was confirmed that its always 16px. I will dig out the tweets where I discussed this.

**Comment by shaunbent** [comment]
Here we go, this was a resource I was pointed to: http://stackoverflow.com/a/29723215

**Comment by kaelig** [comment]
Merci for using Sass MQ, Florent.

You're right, in most cases this is a non-issue.

The BBC and the Guardian, who are using this mixin are serving content to thousands of different devices with a huge variety of versions of Chrome, Safari, and other WebKit forks. In this context, it still is an issue, especially for BBC World Service who reaches many developing countries (you'd be surprised to see what people use to surf the web in Indonesia!).

Feel free to fork the project to make it fit for your needs, or open a PR if you feel strongly that choosing between em/px units should be a config option.

**Comment by fvsch** [comment]
@shaunbent, you write:

> Media queries defined with em are always based off 16px no matter what the base font size is set to.

Which your source actually disproves:

> the em unit [in media queries] is relative to the initial value of font-size, defined by the user agent or the user’s preferences

For user agents, by convention that's 16px. But users may change their browser config to something else, and in that situation the media queries converted to `em` units would probably not match the author's intentions (if browsers do follow the spec).

**Comment by davidhund** [comment]
Yes. If I'm not mistaken `em` values in media-queries are *always* evaluated relative to the **UA** font-size setting (most often ~16px, but could be changed).

So `1em` is *not* “always 16px”, but *is* always the *UA base font-size* setting…
(It takes the UA base font-size, *not* the `:root` font-size defined in your CSS)

Consider the following:
-  Your *default* UA's base font-size (`1em ~=  16px`)
- `:root { font-size: 125%; }` in your CSS (`1em ~=  20px`)
- and also: `@media all and ( min-width: 30em ) { .. stuff .. }`

Now you would expect the MQ (`stuff`) to apply at *~600px* (30 * 20), **but the MQ will apply at *~480px* (30 * *16*)**

http://codepen.io/davidhund/full/wayPRe/

Now change your UA default font-size to e.g. ‘Large’ and visit: http://codepen.io/davidhund/full/Nqywoa (pixels). The color will change at 600px but your font is much larger (as are em-based layout things such as padding etc).

Which is why IMO there _is_ value in `em`-based media-queries: they do not ‘break’ when UA base font-size settings are changed and IMO do “match the author's intentions”…

But now that the old zooming bug is fixed it's mostly a personal preference anyhow ;-)

**Comment by fvsch** [comment]
> So 1em is not “always 16px”, but is always the UA base font-size setting…

To be exact, it's the *user's* base font-size. (UA --> User --> Author styles).

> Which is why IMO there is value in em-based media-queries: they do not ‘break’ when UA base font-size settings are changed and IMO do “match the author's intentions”

They only match the author's intentions if authors have been careful to implement the whole site using `em`, or maybe `rem` (but they must not change the `font-size` of the root element in this case, so that it keeps matching the user's base font-size), and percentages.

This is an authoring bug that sass-mq creates:

```scss
$mq-breakpoints: (
    desktop: 980px
);

@import 'lib/sass-mq/mq';

body {
    @include mq($from: desktop) {
        width: 960px;
        margin: 0 auto;
    }
}
```

Will be converted to:

```css
@media (min-width: 60em) {
    body {
        width: 960px;
        margin: 0 auto;
    }
}
```

If the user's base font-size is indeed 16px, then the body will have a fixed 960px width for viewport widths of 980px and more. All is well. But if the user set up their browser to use a base font size of 24px, this width of 960px will only be triggered for viewports that are 1440px wide and beyond. Which is not ideal. Especially if below this breakpoint the container's width is set to something even smaller, like 600px -> you end up with a 600px column inside a 1360px viewport, for instance.

Of course if the user has set their base font-size to 14px (whether that's intentional or a mistake), the 60em query means 800px, so at viewports between 800px and 960px you get content that overflows the viewport (fixed 960px width in that example).

**Comment by davidhund** [comment]
Fair point @fvsch.
I've personally never ran into those issues because I author much based on `em`…
I can see how this could cause strange ‘bugs’.

I guess there's something to say for avoiding mixing units. 
Perhaps sass-mq could offer a `$mq-unit` setting?

**Comment by kaelig** [comment]
I recommend using `rem` units in combination with `em` media queries so that the whole UI is zoomed as the user changes their text size preference. The Guardian website is a good example of that behaviour.

If you see a use case where this would be an anti-pattern, can you please build a reduced test case that would show why?

**Comment by davidhund** [comment]
@kaelig That would be my approach too, but I believe @fvsch makes a fair point: combining ‘absolute’ `px` sizes with ‘relative’ font-size based units could cause unexpected results. 

Being very prescriptive in what sizing units people use is one way, but could easily be avoided with a setting, no?

**Comment by fvsch** [comment]
@kaelig If you size containers using `rem` units, you will avoid this issue *but only if the root font-size is not changed by the author styles*. If you have a `html { font-size: 62.5% }` or `html { font-size: 125% }` for instance, you're in a bad place. :)

Currently with sass-mq you're helping users who zoom on old WebKits and possibly breaking things for users who change the base font-size in any browser. That's an alright compromise to make.

One option would be to introduce a setting to enable em conversion, that would be on by default. (And perhaps, in a future major version, it might be a possibility to set it to false by default.)

**Comment by kaelig** [comment]
As far as I remember, The Guardian's root font-size [used to be set to 62.5%](https://github.com/guardian/guss-typography/blob/1467df799435c6e8bea9c2a96037a4bd2579ea0a/README.md#suggested-default-type-settings) and everything scaled very well.

Please provide reduced tests cases showing where things break, and where ems are considered harmful. I'll be happy to review them and will consider adding a parameter.

**Comment by fvsch** [comment]
> As far as I remember, The Guardian's root font-size used to be set to 62.5% and everything scaled very well.

Indeed I got it mixed up. -__-
It's only with `html { font-size: 16px` } or any unit other than a proportional one that things go bad.

**Comment by fvsch** [comment]
I wrote [a few test cases](http://fvsch.com/code/em-media-queries/). They all involve having em in media queries and some content sized in pixels. For these tests I've used `width` mostly, and I'll agree that ideally people should use `max-width` to mitigate such problems, but I doubt people use `max-width` systematically *just in case*. Similarly, people might want to size blocks (when fixed widths are needed at some breakpoints) using `rem` over `px`, but that’s not the most common situation either.

The most comprehensive example, using several breakpoints (all in em as if generated by sass-mq) is this one: http://fvsch.com/code/em-media-queries/issue-3
Testing with a base font-size of 14px instead of 16px shows some pretty real problems. With a base font-size that is bigger than the conventional 16px, we're running into problems too, but it's mostly extra space, so it’s not as bad.

**Comment by kaelig** [comment]
Dear all, can you please test the new version beta?

```
$ npm install sass-mq@^3.3.0

# or 

$ bower install sass-mq@^3.3.0
```

```scss
// Override width handling with pixels
@function mq-width-override($px, $base-font-size) {
  @if unitless($px) {
    @return $px * 1px;
  }
  @if unit($px) == em {
    @return $px / 1em * $base-font-size;
  }
  @return $px;
}

@import 'path/to/mq';
```

Let me know how this works out for you!
