### ISSUE TITLE
Error: media query expression must begin with '('

### ISSUE THREAD

**Issue by davidangel** [sass-mq/sass-mq#70]
I'm getting this error with the latest version of node:

    Error: my/path/to/_mq.scss
    218:50  media query expression must begin with '('

I'm not even sure what dependency might be at fault here, so I'm sorry if I'm way off. Any ideas about why this might be occurring?

**Comment by kaelig** [comment]
Thanks for reporting this, can you list the versions of node-sass, node and npm that are used on the machine so that I can recreate the environment?

**Comment by davidangel** [comment]
gulp-sass: ^2.0.4 (node-sass: ^3.0.0)
    node: 4.2.1
    npm: 2.14.7

Probably should have mentioned those details on the frontend. :-)

**Comment by kaelig** [comment]
Thank you again! I will have a look in a few days when I have access to a dev machine again.

**Comment by davidangel** [comment]
A closer look into our code base revealed that we had called the _mq mixing in some places with three arguments. This resulted in the error mentioned here. This appears to be a non-issue, unless you'd like to improve error messaging. Thanks!

**Comment by kaelig** [comment]
Thank you, and no problem at all. I will close this, but thank you for the suggestion: if this comes back again I might look into improving warning messages.

**Comment by halt-hammerzeit** [comment]
I'm having this error too.
My code:

```
@media all and (min-width: 901pt)                          { @import "l-xl.scss" }
@media all and (min-width: 601pt)  and (max-width: 901pt)  { @import "m-l.scss"  }
@media all and (min-width: 241pt)  and (max-width: 900pt)  { @import "s-m.scss"  }
@media all                         and (max-width: 900pt)  { @import "xs-m.scss" }
@media all                         and (max-width: 600pt)  { @import "xs-s.scss" }

@media all and (min-width: 1601pt)                         { @import "xl.scss" }
@media all and (min-width: 901pt)  and (max-width: 1600pt) { @import "l.scss"  }
@media all and (min-width: 601pt)  and (max-width: 900pt)  { @import "m.scss"  }
@media all and (min-width: 241pt)  and (max-width: 600pt)  { @import "s.scss"  }
@media all                         and (max-width: 240pt)  { @import "xs.scss" }
```

**Comment by kaelig** [comment]
@halt-hammerzeit is this related to sass-mq?

**Comment by halt-hammerzeit** [comment]
oh, I missed the project apparently.
I'll open an issue in `node-sass`

**Comment by kaelig** [comment]
No problem. Looking at the code provided: I'm not sure Sass allows importing inside media queries.
