### ISSUE TITLE
Function mq-get-breakpoint-width finished without @return

### ISSUE THREAD

**Issue by codev0** [sass-mq/sass-mq#74]
Hey.

I have `Function mq-get-breakpoint-width finished without @return` issue.

**Comment by kaelig** [comment]
Thank you for using sass-mq!

Can you please provide the code that runs and I'll try to help.

**Comment by kaelig** [comment]
Closing as this is a few weeks old without getting any additional info.

**Comment by halo** [comment]
Turns out, this error occurs when you try to use a breakpoint name that has not been defined and you happen to [not see the warning](https://github.com/sass-mq/sass-mq/blob/47cd6b1156d35a702edd3fbed0bcd285dcd95d29/_mq.scss#L117) somewhere in the log higher up.
