### ISSUE TITLE
mq(hdpi) and height

### ISSUE THREAD

**Issue by ryuran** [sass-mq/sass-mq#75]
Hello,

I use Sass-mq on several project.
I would use it for some other rules.
* min and max height
* hdpi

Can it be added ?

**Comment by kaelig** [comment]
Thank you for using sass-mq, @ryuran. 

min and max height can be added using the `$and` parameter. The reason why these use cases are not supported with their own parameters is the IE8 support (the fallback wouldn't work). 

When it comes to hidpi, have you checked my other project? GitHub.com/kaelig/hidpi

**Comment by ryuran** [comment]
Thanks @kaelig. I give a look to your hidpi mixin.
