### ISSUE TITLE
Problems with responsive elements not snapping in place after browser resize

### ISSUE THREAD

**Issue by coffeeneed** [sass-mq/sass-mq#81]
Hi!

I posted this in the at the Jeet.gs repo: https://github.com/mojotech/jeet/issues/461

Anyone know if this can be a sass-mq issue? 

Thanks :)

**Comment by shaunbent** [comment]
I'm sure this is not a problem with `sass-mq` and is more likely to be user error.

**Comment by kaelig** [comment]
Hi @coffeeneed, thanks for using sass-mq!

Not sure this is related to sass-mq directly but can you please share a reduced demo of the bug so we can have a look at it?

**Comment by kaelig** [comment]
Closing this issue as it hasn't been updated in about a month. Feel free to reopen if you are still encountering this problem.
