### ISSUE TITLE
Add ability to specify predefined values for `$and`

### ISSUE THREAD

**Issue by TxHawks** [sass-mq/sass-mq#82]
I think it makes sense to be able to specify a media-query name in the `$and` parameter, rather than a string. It is a much better fit for the bridging-the-gap-between-designers-and-developers philosophy.

After all, when people want to display a different image on high density screens, they mostly think of it as 'lets show a higher resolution image on `retina` or `hidpi`', not as 'lets show a higher resolution image on `(-webkit-min-device-pixel-ratio:  1.3), (min-resolution: 120dpi), (min-resolution: 1.3dppx)`'.

Writing `@include mq($and: hidpi)` is much more reasonable than writing. `@include mq($and: '(-webkit-min-device-pixel-ratio:  1.3), (min-resolution: 120dpi), (min-resolution: 1.3dppx)')`, especially for designers.

The way I see it, there are three easy ways to achieve this:

1. Simply having the `mq` mixin search the `$mq-breakpoints` map, and define the rules there.  
    **Downside:** it makes is harder for people to loop over the `$mq-breakpoints` map if they want to for some reason. Looping could still be done by testing if the value of the key to be a number, but it adds another validation step. I guess this makes it a breaking change.
2. Adding a second map, say `$mq-misc-breakpoints`, where miscellaneous breakpoints would be defined. If choosing this path, perhaps `$mq-breakpoints` should be renamed to `$mq-width-breakpoints`, though this should be considered a breaking change.  
**Downside:** Requires managing two definition maps, higher cognitive load.
3. Splitting the the `$mq-breakpoints` map into two sub-maps:

   ```scss
   $mq-breakpoints: (
      widths: (   // maybe lengths is a better name?
        mobile: 320px,
        // etc.
      ),
      misc: (     // Maybe features?
        landscape: '(orientation: landscape)',
        // etc.
      ),
   ) !default;
   ```   
  **Downside:** I think this is the best approach, but It's a breaking change

If you think this is a worthy change, I'll be happy to submit a pull request

**Comment by kaelig** [comment]
Thank you for using sass-mq, @TxHawks.

This is an interesting suggestion but isn't that something that would be doable using variables?

```scss
$hidpi: (-webkit-min-device-pixel-ratio: 1.3), (min-resolution: 120dpi), (min-resolution: 1.3dppx);

@include mq($and: $hidpi) {
}
```

PS: you might want to look into this too: https://github.com/kaelig/hidpi

**Comment by TxHawks** [comment]
I do know and like `hidpi` (and the rest of your work), and yes, of course, it could be done with a variable, same way the length definitions could technically be done with variables. However, I think that the idea of having a map is to offer better organization and lowering the cognitive overload.

I think this is especially helpful for designers, who can reasonably just expect their media-query to work in a consistent manner across `$from`, `$until` and `$and`. There is no logical reason to assume you could do `$until: table`, but would need to do `$and: $hidpi`.

It's just not consistent. 

Not a huge deal, but I think it would be an improvement.

**Comment by kaelig** [comment]
Adding such functionality for `$and` as a "core feature" means we need to deal with it correctly when "responsive mode" is turned off. And on the top of my head I'm not sure how we'd do that.

Closing this as the functionality is something that's already doable in other ways.
