### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by peterklein** [sass-mq/sass-mq#87]
Some CSS parsers will break, when using the "mq-show-breakpoints" mixin. The reason for this is the "≥" sign. I used this in a CoreMedia system which minified the css and breaked then on this part

**Comment by kaelig** [comment]
Sorry to hear this! If you manage to find a fix, can you submit a pull request (or let us know what the fix is)?

**Comment by kaelig** [comment]
Looks like there is a solution but I think it's the responsibility of other systems to fix it.

https://github.com/mesmerismo/sass-mq/commit/4d94911910a72d5b36105f5076e94b3dd41af1d8
