### ISSUE TITLE
My company uses Sass MQ

### ISSUE THREAD

**Issue by Nazcange** [sass-mq/sass-mq#88]
Hi, we're using Sass MQ at Le Figaro for the site [tvmag.lefigaro.fr](http://tvmag.lefigaro.fr) and we'd like to be mentionned in the README of the project. Cheers!

**Comment by hllwd** [comment]
http://tvmag.lefigaro.fr actually

**Comment by lucascherifi** [comment]
@Nazcange Try a PR :)

**Comment by kaelig** [comment]
Merci for the ping, glad to see Sass MQ is useful for other newspapers!
