### ISSUE TITLE
How to import sass-mq in a project when installed from npm

### ISSUE THREAD

**Issue by certainlyakey** [sass-mq/sass-mq#89]
Hi! I installed `sass-mq` with npm using `npm install sass-mq --save` and tried all the combinations then to import it in a SASS file. These are:

- `@import '_mq';`
- `@import 'mq';`
- `@import '_sass-mq';`
- `@import 'sass-mq';`
- `@import '_mq()';`
- `@import 'mq()';`
- `@import 'sass-mq/mq';`.

Only the "full" path version `@import './node_modules/sass-mq/_mq';` has worked. Still, is there a standard alias that we can use?

**Comment by kaelig** [comment]
Hi @certainlyakey, thank you for using Sass MQ!

Have you tried using [Eyeglass](https://github.com/sass-eyeglass/eyeglass) to load Sass MQ?

Then your import should look like this:

```scss
@import 'sass-mq';
```

**Comment by certainlyakey** [comment]
Hi! Thanks for the answer. I thought it was optional to use eyeglass? So that's the only way to import it that "simple" way, right?

**Comment by kaelig** [comment]
You are correct, it is optional to use Eyeglass.

As an alternative, you may want to look into `includePath` in node-sass. Hope this helps!

**Comment by certainlyakey** [comment]
OK, thanks!

**Comment by benrich** [comment]
Don't ask me why but `'~sass-mq'` worked for me.

Although 6 years later @use is recommended now
