### ISSUE TITLE
My company uses Sass MQ

### ISSUE THREAD

**Issue by csswizardry** [sass-mq/sass-mq#90]
Hi, we're using Sass MQ at [inuitcss](https://github.com/inuitcss/inuitcss) and we'd like to be mentioned in the README of the project. Cheers!

**Comment by phamann** [comment]
No.

**Comment by kaelig** [comment]
Thanks for using Sass MQ! Fixed in 8ac052f9d19d9bbcc907c1616ad99543d30a462b :)
