### ISSUE TITLE
$mq-show-breakpoints not working.

### ISSUE THREAD

**Issue by HarveyWilliams** [sass-mq/sass-mq#94]
I'm using:

```
@include mq-add-breakpoint(xsmall, 600px);
@include mq-add-breakpoint(small, 768px);
@include mq-add-breakpoint(medium, 992px);
@include mq-add-breakpoint(large, 1024px);
@include mq-add-breakpoint(xlarge, 1200px);

$mq-show-breakpoints: (xsmall, small, medium, large, xlarge);
```

But no `:before` element is appearing on my body element in the browser (tested on FF49 and Chrome 54).

Am I using MQ right? I can see the original pull request here: https://github.com/sass-mq/sass-mq/pull/7

**Comment by kaelig** [comment]
Thank you for the question and for using Sass MQ, @HarveyWilliams!

Adding this at the end of the file should help:

```scss
@include mq-show-breakpoints;
```

This is an undocumented feature, apologies for the inconvenience!

****

However, I'd recommend using Sass MQ like this:

```scss

$mq-breakpoints: (
    xsmall:  600px,
    small:   768px,
    medium:  992px,
    large:   1024px,
    xlarge:  1200px
);

$mq-show-breakpoints: (xsmall, small, medium, large, xlarge);

@import 'mq';
```

This way, $mq-breakpoints will only contain your breakpoints and not the default ones.

**Comment by HarveyWilliams** [comment]
Thanks @kaelig. I updated the readme to reflect the information you shared with me: https://github.com/sass-mq/sass-mq/pull/96
